UPLOAD_DIR = "data/uploads"

FAN_OUT = 15           # number of target peaks per anchor
MIN_TIME_DELTA = 1
MAX_TIME_DELTA = 200

# Audio Streaming parameters
DEFAULT_SR = 22050
DEFAULT_HOP_LENGTH = 512
DEFAULT_N_FFT = 2048
DEFAULT_AMP_MIN = -60
DEFAULT_NOISE_FLOOR_DB = -75
DEFAULT_LOWPASS_CUTOFF = 8000
BUFFER_SECONDS = 15
CHUNK_SIZE = 1024 
