kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: shanano
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000 # api NodePort
        hostPort: 30000
        protocol: TCP
      - containerPort: 30001 # worker NodePort
        hostPort: 30001
        protocol: TCP
      - containerPort: 30900 # prometheus NodePort
        hostPort: 30900
        protocol: TCP
      - containerPort: 30030 # grafana NodePort
        hostPort: 30030
        protocol: TCP
