"""create songs and fingerprints tables

Revision ID: 8213ee7ae066
Revises: 
Create Date: 2026-07-31 00:36:48.912248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8213ee7ae066'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fingerprints',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('anchor_time', sa.Integer(), nullable=False),
    sa.Column('anchor_freq', sa.Integer(), nullable=False),
    sa.Column('target_time', sa.Integer(), nullable=False),
    sa.Column('target_freq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hash', 'song_id')
    )
    op.create_index(op.f('ix_fingerprints_hash'), 'fingerprints', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fingerprints_hash'), table_name='fingerprints')
    op.drop_table('fingerprints')
    op.drop_table('songs')
    # ### end Alembic commands ###
