"""add catalog metadata to songs

Revision ID: a3f0d86e1588
Revises: f8aa4bb84303
Create Date: 2026-08-01 19:27:56.149892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f0d86e1588'
down_revision: Union[str, Sequence[str], None] = 'f8aa4bb84303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('album', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('cover_art_url', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('source', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('source_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_songs_source_url'), 'songs', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_source_url'), table_name='songs')
    op.drop_column('songs', 'source_url')
    op.drop_column('songs', 'source')
    op.drop_column('songs', 'cover_art_url')
    op.drop_column('songs', 'genre')
    op.drop_column('songs', 'year')
    op.drop_column('songs', 'album')
    op.drop_column('songs', 'artist')
    # ### end Alembic commands ###
