"""add status and file_path to songs

Revision ID: f8aa4bb84303
Revises: 8213ee7ae066
Create Date: 2026-07-31 01:12:22.111663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8aa4bb84303'
down_revision: Union[str, Sequence[str], None] = '8213ee7ae066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('songs', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'file_path')
    op.drop_column('songs', 'status')
    # ### end Alembic commands ###
